### ISSUE TITLE
Minidec Panics

### ISSUE THREAD

**Issue by Tenebryo** [radareorg/radeco#39]
I ran into a couple panics when running `minidec`. I'm using rustc version `rustc 1.13.0-nightly (a7b2232d2 2016-09-07)`.

First at the very beginning of the run I get the following panic. Execution, however, continues.

```
...
[*] Constructing ...
thread '<unnamed>' panicked at 'not yet implemented', /home/sam/.cargo/git/checkouts/esil-rs-86f6c3f12c1d8ed5/master/src/parser.rs:166
stack backtrace:
   1:     0x7f59e6083923 - std::sys::backtrace::tracing::imp::write::h46f28e67d38b4637
   2:     0x7f59e60877fd - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:     0x7f59e6086a8a - std::panicking::default_hook::h96c288d728df3ebf
   4:     0x7f59e6087088 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:     0x7f59e604d1ff - std::panicking::begin_panic::h0914615a412ba184
   6:     0x7f59e604eb9f - <esil::parser::Parser as esil::parser::Parse>::fetch_operands::h4f14395fe3fda996
   7:     0x7f59e6041b6e - <radeco_lib::frontend::ssaconstructor::SSAConstruct<'a, T>>::run::h2ddb588b2a2b0311
   8:     0x7f59e6046664 - radeco_lib::frontend::containers::ssa_single_fn::he1c8cf8aa5ab0a43
   9:     0x7f59e6014822 - std::panicking::try::do_call::h1c70469e16982e0c
  10:     0x7f59e608f2c6 - __rust_maybe_catch_panic
  11:     0x7f59e6019e84 - <F as alloc::boxed::FnBox<A>>::call_box::hc5ae4f213bb2fd4e
  12:     0x7f59e60859b0 - std::sys::thread::Thread::new::thread_start::h5b631f48cd23f128
  13:     0x7f59e57d8183 - start_thread
  14:     0x7f59e52da37c - clone
  15:                0x0 - <unknown>
```

Some functions seem to be decompiled correctly, but at least one (always seems to be from a small subset of the functions in the binary) panics in the following way:

```
...
  [*] Writing out IR
thread 'main' panicked at 'assertion failed: i == ssa.regnames.len()', src/middle/ir_writer.rs:383
stack backtrace:
   1:     0x7f59e6083923 - std::sys::backtrace::tracing::imp::write::h46f28e67d38b4637
   2:     0x7f59e60877fd - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:     0x7f59e6086a8a - std::panicking::default_hook::h96c288d728df3ebf
   4:     0x7f59e6087088 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:     0x7f59e60147af - std::panicking::begin_panic::h0914615a412ba184
   6:     0x7f59e600c243 - radeco_lib::middle::ir_writer::IRWriter::emit_il::h0527167121961ec6
   7:     0x7f59e602330d - minidec::main::h87fa1fd4e3efb403
   8:     0x7f59e608f2c6 - __rust_maybe_catch_panic
   9:     0x7f59e6086301 - std::rt::lang_start::haaae1186de9de8cb
  10:     0x7f59e5201f44 - __libc_start_main
  11:     0x7f59e6009288 - <unknown>
  12:                0x0 - <unknown>
```

After this panic, `minidec` stops and produces an incomplete output.

**Comment by sushant94** [comment]
Hey! Thanks for this. The first one seems to be because the binary has an ESIL instruction that has not been implemented in esil.rs yet.

I'll look into the second one. Is it possible for you to share the bin or provide logs? If not, is there any way you can write a function similar to the one it panics on? It seems to me that there is a register not present in the regfile of radeco, and hence that panic.

Thanks.

**Comment by Tenebryo** [comment]
@sushant94 

I don't have the code for the binary, as it was part of a CTF. However, the binary can be downloaded [from the ctf site, here.](https://twctf7qygt6ujk.azureedge.net/uploads/diary-999cc49df002db99154b4c572713f5c91f2d112b139bdbfe4a34f5deab35337a) 

I hope this helps!

**Comment by XVilka** [comment]
I guess this one can be closed now?

**Comment by ZhangZhuoSJTU** [comment]
Yep, closed.
